language: ruby
sudo: false
env:
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=4.1.0"
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0.beta1"
rvm:
  - 2.0
  - 2.1.7
  - 2.2.3
matrix:
  exclude:
    - env: "RAILS_VERSION=5.0.0.beta1"
      rvm: 2.0
    - env: "RAILS_VERSION=5.0.0.beta1"
      rvm: 2.1.7
before_script:
  - cp spec/database.yml.sample spec/database.yml
